### ISSUE TITLE
Install fails on Mac

### ISSUE THREAD

**Issue by GeoffreyPlitt** [overview/overview-js-bloom-filter#1]
```
giro@Geoffreys-iMac:~/stardust-backend$yarn add overview-js-bloom-filter
yarn add v0.23.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠠ overview-js-bloom-filter:                               ^
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
error /Users/giro/stardust-backend/node_modules/overview-js-bloom-filter: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/giro/stardust-backend/node_modules/overview-js-bloom-filter
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@7.6.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/Cellar/yarn/0.23.4/libexec/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/giro/stardust-backend/node_modules/overview-js-bloom-filter/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/yarn/0.23.4/libexec/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/giro/.node-gyp/7.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/giro/.node-gyp/7.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/yarn/0.23.4/libexec/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/giro/stardust-backend/node_modules/overview-js-bloom-filter',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bloomfilter/src/bloomfilter.o
In file included from ../src/bloomfilter.cc:1:
../src/BloomFilter.hpp:17:20: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
  ~BloomFilter() { delete buckets; }
                   ^
                         []
../src/BloomFilter.hpp:12:13: note: allocated with 'new[]' here
    buckets(new char[nBuckets / 8 + (nBuckets % 8 ? 1 : 0)])
            ^
../src/bloomfilter.cc:61:37: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    args.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                    ^
/Users/giro/.node-gyp/7.6.0/include/node/v8.h:3658:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
../src/bloomfilter.cc:97:24: warning: 'ToUint32' is deprecated [-Wdeprecated-declarations]
      begin = args[1]->ToUint32()->Value();
                       ^
/Users/giro/.node-gyp/7.6.0/include/node/v8.h:9035:22: note: 'ToUint32' has been explicitly marked deprecated here
Local<Uint32> Value::ToUint32() const {
                     ^
../src/bloomfilter.cc:100:22: warning: 'ToUint32' is deprecated [-Wdeprecated-declarations]
      end = args[2]->ToUint32()->Value();
                     ^
/Users/giro/.node-gyp/7.6.0/include/node/v8.h:9035:22: note: 'ToUint32' has been explicitly marked deprecated here
Local<Uint32> Value::ToUint32() const {
                     ^
../src/bloomfilter.cc:124:26: error: no matching function for call to 'New'
  Local<Object> buffer = node::Buffer::New(isolate, &data[0], data.length());
                         ^~~~~~~~~~~~~~~~~
/Users/giro/.node-gyp/7.6.0/include/node/node_buffer.h:46:40: note: candidate function not viable: 2nd argument ('const value_type *' (aka 'const char *')) would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/giro/.node-gyp/7.6.0/include/node/node_buffer.h:34:40: note: candidate function not viable: no known conversion from 'const value_type *' (aka 'const char *') to 'v8::Local<v8::String>' for 2nd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/giro/.node-gyp/7.6.0/include/node/node_buffer.h:31:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/giro/.node-gyp/7.6.0/include/node/node_buffer.h:39:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
../src/bloomfilter.cc:165:29: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> ret = cons->NewInstance(2, argv);
                            ^
/Users/giro/.node-gyp/7.6.0/include/node/v8.h:3658:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
5 warnings and 1 error generated.
make: *** [Release/obj.target/bloomfilter/src/bloomfilter.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/yarn/0.23.4/libexec/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Users/giro/.nvm/versions/node/v7.6.0/bin/node" "/usr/local/Cellar/yarn/0.23.4/libexec/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/giro/stardust-backend/node_modules/overview-js-bloom-filter
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
```

**Comment by adamhooper** [comment]
Thank you for reporting this! Could you please try installing v0.0.3? I think I've fixed these errors. I've tested on Node 8 on Linux.
